### ISSUE TITLE
closing long position in current holdings

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#10]
In create orders, action has ORDER_ACTION_BUY('BUY') ,ORDER_ACTION_SELL('SELL'). 
 What is c**losing of  long position in current holding**s?

Best regards,
Ingyu

**Comment by foonsun** [comment]
@igkoh  You can use "quantity" field to indicate long or short.https://github.com/hbdmapi/hbdm_Python/blob/master/alpha/platforms/huobi_swap_trade.py#L277
