### ISSUE TITLE
Differences between Futures and Swap

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#13]
1. strategy.py futures have **quarterly, weekly, ... of different maturit**y, while **perpetual swap has only one(BTC-USD**)   
2. future and swap  have different **uri :uri = "/api/v1/contract_cancel"   vs   uri = "/swap-api/v1/swap_cancel"**  
3. future and swap  have different **wss:  self._wss + "/ws"  vs  self._wss + "/swap-ws"**
**Why future and swap have different uri and wss addresses**?
**Purely from the programmer's viewpoint, future and swap have the same structures except symbol.  I want to understand what decision have two different uri and wss for future and swap separately.**
Best regards,
Ingyu

**Comment by foonsun** [comment]
@igkoh Hi, Future and Swap are similar just as you said.Swap is another system,the uri and wss addresses are different.The swap has some features,such as funding fee, etc.

**Comment by igkoh** [comment]
Dear foonsun,
  From your kind explanation, I appreciate substantial differences between futures and swaps other than code names.  Where can I find **api for funding rate in swap**, as well as **open interests in futures and swaps**?
**Number of long and short position related to funding rate** would be valuable if available in api.
Best regards,
Ingyu

**Comment by foonsun** [comment]
@igkoh Hi, this project still doesn't contain api for funding rate in swap and open interests.It will be available in the next version.What do you mean of **Number of long and short position related to funding rate** ?

**Comment by igkoh** [comment]
If long position outnumbers short position significantly in swap, funding rate controls it by negative incentives of funding rate.  In futures, expiration at  maturity date controls the deviation between future price and index.  But in perpetual swap, absence of expiration at maturity date requires additional negative incentive of funding rate.

**Comment by foonsun** [comment]
@igkoh Thanks for your precise answer. Can these apis meet your needs:https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#subscribe-basis-data?

**Comment by igkoh** [comment]
Thanks for docs.
