### ISSUE TITLE
ssl:default [Address family not supported by protocol]

### ISSUE THREAD

**Issue by qq71151461** [hbdmapi/hbdm_Python#14]
环境：阿里云香港专有网络，centos6 python3.7
运行时，websocket 连接报以下错误：
ssl:default [Address family not supported by protocol]

**Comment by foonsun** [comment]
可能与SSL库有关；
尝试步骤：
不使用ssl加密地址，即使用ws://api.hbdm.vn来测试是否正常；如果正常说明可能是ssl模块问题，需要检查SSL模块；
