### ISSUE TITLE
large number of revoke_order

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#15]
If there are 300 order nos to cancel of offset=close, should I **put time.sleep(0.001)** [ 1/1000 second ] between or
**async/await handles in loop queue automatically** in 30 consecutive revoke_order?

Best regards,
Ingyu

**Comment by foonsun** [comment]
@igkoh You can put time.sleep(0.001) when there are 300 order nos to cancel of offset=close. Pls be noted that the API Rate Limit Illustration:https://huobiapi.github.io/docs/dm/v1/en/#api-rate-limit-illustration
