### ISSUE TITLE
Tick size 0.01 for Futures and 0.1 for Swaps

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#16]
**One tick in futures is 0.01, and 0.1 for swaps**.   From market maker viewpoints, **futures expose more opportunities of ask/bid to be filled by takers**,  Thus more market makers participate into the market to provide better liquidity.  I am curious **why** Huobi makes a decision of 0.1 tick in swaps.
Best regards,
Ingyu

**Comment by foonsun** [comment]
@igkoh The reason that Huobi makes a decision of 0.1 tick in swaps is that the liquidity will be better under the extreme market.

**Comment by igkoh** [comment]
Thanks, foonsun.   Since **both swaps and futures** have forced liquidation for the high leveraged position, 0.1 and 0.01 tick of swaps and futures provides **same liquidity.**
Reasoning is : **sum of liquidity in 10 ticks(0.01) of futures = liquidity of 1 ticks (0.1 ) swaps**.  **Thus why swaps have more problems in the extreme market**?   By funding rate,
swap price - index is controlled as expiration  of future market restricts future price-index.
Best regards,
Ingyu

**Comment by foonsun** [comment]
@igkoh The slippage is lower if the tick is 0.1. It's simliar with BitMex.
