### ISSUE TITLE
Swaps : [AsyncHttpRequests] response data is not json format!

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#17]
Thanks for solving many problems in exploring huobi futures.  Extending market making into swaps,
the following problems occurred:

_(base) E:\BitCoin2\hbSwpDS14\hbdm_Python\examples\huobi_swap>python main.py config.json
init logger ...
I [2020-08-05 07:26:07,324] [-] [Quant] version: 1.0.13_200716_alpha
I [2020-08-05 07:26:07,831] [-] [Quant] start io loop ...
I [2020-08-05 07:26:07,833] [-] [HuobiSwapTrade] url: wss://api.hbdm.vn/swap-notification
I [2020-08-05 07:26:08,039] [-] [HuobiSwapMarket] url: wss://api.hbdm.vn/swap-ws
W [2020-08-05 07:26:08,499] [-] [AsyncHttpRequests] response data is not json format! method: POST url: https://api.hbdm.vn/swap-api/v1/swap_openorders headers: {'Accept': 'application/json', 'Content-type': 'application/json', 'User-Agent': 'AlphaQuant1.0.13_200716_alpha'} params: {'AccessKeyId': '5813b5f3-0a6ba013-ghxertfvbf-ff37b', 'SignatureMethod': 'HmacSHA256', 'SignatureVersion': '2', 'Timestamp': '2020-08-04T22:26:08', 'Signature': '6N40uVRA5Q96sL1YFhar7CIj195DV+spQ2FwGHRIzYQ='} body: None data: {'contract_code': 'BTC-USD', 'page_index': 1, 'page_size': 50} code: 200 result: {"status":"ok","data":{"orders":[],"total_page":1,"current_page":1,"total_size":0},"ts":1596579968669}
KeyboardInterrupt (ID: 2) has been caught. Cleaning up..._

Call stack shows:
![notJasonFormat](https://user-images.githubusercontent.com/58127244/89352636-8da2b580-d6ef-11ea-80fe-ea92522a4023.png)

Best regards,
Ingyu

**Comment by igkoh** [comment]
he same request.py in alpha/utils functions **properly in futures** as 
(base) E:\BitCoin2\hbSwpDS14\hbdm_Python\examples\huobi_future>python main.py config.json
_init logger ...
I [2020-08-05 07:29:28,243] [-] [Quant] version: 1.0.13_200716_alpha
I [2020-08-05 07:29:28,717] [-] [Quant] start io loop ...
I [2020-08-05 07:29:28,718] [-] [HuobiFutureTrade] url: wss://api.hbdm.vn/notification
I [2020-08-05 07:29:28,911] [-] [HuobiFutureMarket] url: wss://api.hbdm.vn/ws
I [2020-08-05 07:29:29,130] [-] [MyStrategy] trade update: {"platform": "huobi_future", "symbol": "BTC_CQ", "action": "BUY", "price": "11554.22000000", "quantity": "4.00000000", "timestamp": 1596580166633}
I [2020-08-05 07:29:29,168] [-] [MyStrategy] position update: [platform: huobi_future, account: ingyukoh@gmail.com, strategy: my_test_strategy, symbol: BTC/quarter, short_quantity: None, short_avg_price: None, long_quantity: 0, long_avg_price: 0, liquid_price: None, utime: 1596580169334]
I [2020-08-05 07:29:29,169] [-] [MyStrategy] position update: [platform: huobi_future, account: ingyukoh@gmail.com, strategy: my_test_strategy, symbol: BTC/quarter, short_quantity: 0, short_avg_price: 0, long_quantity: 0, long_avg_price: 0, liquid_price: None, utime: 1596580169334]
I [2020-08-05 07:29:29,322] [-] [MyStrategy] asset update: {"platform": "huobi_future", "account": "ingyukoh@gmail.com", "assets": {"BTC": {"total": "0.00000000", "free": "0.00000000", "locked": "0.00000000"}}, "timestamp": 1596580169321, "update": true}
I [2020-08-05 07:29:29,543] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 28.0, 11554.21, 2740.0, 1253.0, 3137.0, 1596580169706]
I [2020-08-05 07:29:29,973] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 28.0, 11554.21, 2740.0, 1168.0, 3137.0, 1596580170134]
I [2020-08-05 07:29:30,220] [-] [MyStrategy] my_test_strategy orders_data []
I [2020-08-05 07:29:30,473] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 28.0, 11554.21, 2740.0, 1187.0, 3137.0, 1596580170635]
I [2020-08-05 07:29:30,948] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 28.0, 11554.21, 2738.0, 1187.0, 3135.0, 1596580171106]
I [2020-08-05 07:29:31,473] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 28.0, 11554.21, 2738.0, 1187.0, 3135.0, 1596580171635]
I [2020-08-05 07:29:31,771] [-] [MyStrategy] my_test_strategy orders_data []
I [2020-08-05 07:29:31,976] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 28.0, 11554.21, 2738.0, 1187.0, 3135.0, 1596580172137]
I [2020-08-05 07:29:32,542] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 28.0, 11554.21, 2738.0, 1257.0, 3135.0, 1596580172706]
I [2020-08-05 07:29:33,043] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 228.0, 11554.21, 2738.0, 1457.0, 3135.0, 1596580173206]
I [2020-08-05 07:29:33,342] [-] [MyStrategy] my_test_strategy orders_data []
I [2020-08-05 07:29:33,576] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 228.0, 11554.21, 2738.0, 1457.0, 3135.0, 1596580173735]
I [2020-08-05 07:29:33,945] [-] [MyStrategy] orderbook update: [11554.22, 11554.21, 11554.22, 228.0, 11554.21, 2738.0, 1457.0, 3135.0, 1596580174107]
KeyboardInterrupt (ID: 2) has been caught. Cleaning up..._

Best regards,
Ingyu

**Comment by foonsun** [comment]
Hi @igkoh  “response data is not json format! “  will be removed in https://github.com/hbdmapi/hbdm_Python/blob/master/alpha/utils/request.py#L75.

**Comment by foonsun** [comment]
The latest version has removed the warning.
