### ISSUE TITLE
代码使用问题

### ISSUE THREAD

**Issue by Lxtluck** [hbdmapi/hbdm_Python#19]
self.last_orderbook_timestamp是如何回调更新的？

**Comment by foonsun** [comment]
@Lxtluck  行情、仓位、订单全部是使用WS订阅回调的方式，比如self._last_orderbook_timestamp是在orderbook进行回调更新的。单位是ms。

```
    async def on_event_orderbook_update(self, orderbook: Orderbook):
        """  orderbook更新
            self.market.orderbooks 是最新的orderbook组成的队列，记录的是历史N次orderbook的数据。
            本回调所传的orderbook是最新的单次orderbook。
        """
        logger.debug("orderbook:", orderbook, caller=self)
        if orderbook.asks:
            self.ask1_price = float(orderbook.asks[0][0])  # 卖一价格
            self.ask1_volume = float(orderbook.asks[0][1])  # 卖一数量
        if orderbook.bids:
            self.bid1_price = float(orderbook.bids[0][0])  # 买一价格
            self.bid1_volume = float(orderbook.bids[0][1])  # 买一数量
        self.last_orderbook_timestamp = orderbook.timestamp
```

**Comment by igkoh** [comment]
Swaps and futures use DIFFERENT orderbook_invalid_seconds as
   swap: orderbook_invalid_seconds=10
  futures: orderbook_invalid_seconds=100

Examinations of 24H volume for swaps and futures are: 36 M and 40 M, approximately of the same size.
Why do you set different time delay criteria for swap and futures?
Best regards,
Ingyu

**Comment by foonsun** [comment]
@Ingyu The invalid seconds is recommended to set 5 or 10 seconds. The seconds:100 is only for test purpose.

**Comment by Lxtluck** [comment]
self.market.klines 是从代码执行开始记录kline信息。我想要代码执行时已有的k线信息，应该怎么取
