### ISSUE TITLE
auth socket没有回复

### ISSUE THREAD

**Issue by fengye607** [hbdmapi/hbdm_Python#2]
host 配置为www.hbdm.com
我在trade中加入log，发现服务器没有返回op为auth的消息
elif op == "auth":
            logger.info('begin to handle auth call back')
            await self.auth_callback(data)
大概是什么原因，可以请教一下吗

**Comment by foonsun** [comment]
@fengye607 订阅订单或者用户信息时，需要鉴权，此时会有auth:https://github.com/hbdmapi/hbdm_Python/blob/master/alpha/platforms/huobi_swap_trade.py#L248 ;订阅行情本身不需要auth,可以把调试开关设置为DEBUG模式，这里可以看到所有回复，https://github.com/hbdmapi/hbdm_Python/blob/master/alpha/platforms/huobi_swap_market.py#L124
