### ISSUE TITLE
FAST execution of CANCEL faster than 1.5 second

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#20]
Market making algorithm is :
  series of 
    _if pattern favoring maker,
	   place limit order as maker
	   
    if pattern predicts **extreme rise/fall**,
	   cancel ask/bid maker order within expected range of movement_
	   
	   This extreme rise/fall movement is VERY FAST, and success of the market maker depends on
       1. prediction of extreme rise/fall based on deep learning based on order books and market trades   
	2. **FAST EXECUTION of CANCEL ask/bid** within range 
   Currently pattern is computed from order books and trade from on_event_orderbook_update and on_event_trade_update of strategy.py 
   and sent through redis(on core 
memory database) to pytorch and sent to back to strategy.py through redis.
   PROBLEM is **FAST EXECUTION of CANCEL.**  
   Currently **cancel_orders in strategy.py handles, awaiting in the queue on its turn to cancel**.  Queue returns to **cancel_orders approximately in 1.5 second in loop.**

    _async def cancel_orders(self):
        self.timePrev=self.timeNow
        self.timeNow=time.time()
        dif=self.timeNow-self.timePrev_
   Is there FASTER way to cancel than this one?

Best regards,
Ingyu

**Comment by foonsun** [comment]
Hi @igkoh Queue returns to cancel_orders approximately **in 1.5 second in loop.** -->  Is the loop include orderbook,trades -> prediction -> redis -> start cancel?

The faster way is still the inferface: cancel_orders.

There isn't another faster interface to cancel orders.

**Comment by igkoh** [comment]
_orderbook,trades -> feature extraction to compress ->redis ->prediction in pytorch -> redis -> start cancel

-------------------------------------------------------                                  --------------------   your codes
                                                       ----------------------------------                       in another server not to overload your program_
													   
on_ticker in strategy.py is registered into LoopRunTask with **interval =1 which is set to 1sec**.
Can I set it to 0.5, 0.1,0.01 through controlled experiment to check any disorderly behaviour in loop?
Do you have ideas why I should not **set the interval to be a very small value like 0.001?**             
Best regards,
Ingyu

**Comment by igkoh** [comment]
orderbook,trades -> feature extraction ->redis ->prediction -> redis ->
start cancel

-------------------------------------------
 --------------------   your codes

------------------------ ---    in other server not to overload your program

Function on_ticker in strategy.py is registered into LoopRunTask with interval
=1 which is set to 1sec.

*Can I set it to 0.5, 0.1,0.01 through controlled experiment to check any
disorderly behavior in loop?Do you have ideas why I should not set the
interval to be a very small value like 0.001?            *
Best regards,
Ingyu

**Comment by foonsun** [comment]
@Ingyu Yes,You can set it to 0.5,0.1,0.01 to check any disorderly behavior in loop. A very small value like 0.001 is not neccessary.You can also register several tickers to check the behavior just like this example:https://github.com/hbdmapi/hbdm_Python/blob/master/examples/huobi_option_mm/strategy.py#L159

**Comment by igkoh** [comment]
@foonsun, 

Following your guidance, I experimented on reducing time lag between decision and cancel in await/async architecture.
Successes of market maker depends on this time lag parameter.

The interval defined in LoopRunTask of tasks.py in alpha is set as
LoopRunTask.register(self.on_ticker, 0.001)##0.01)##0.5) ##1) ##2).

The following table shows:
interval         time lag between decision and cancel
2 sec             1.5 sec
1                 0.74
0.5               0.38
0.1               0.005

5 milli second between decision and cancel is GREAT.
Upon setting interval 0.001, function ticker in heartbeat.py in alpha triggers error as
in loop of tasks.items() 
              if self._count % int(interval*200) != 0:
                continue
Thus interval 1/200 sec = 0.005 sec for interval.

**Comment by foonsun** [comment]
@igkoh Thank you!We appreciate that you participated in this test.
