### ISSUE TITLE
trader.revoke_order() in futures and swaps

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#21]
The revoke_order()  without *order_nos **cancels ALL in futures**
_, errors = await self.trader.revoke_order()##*order_nos).

In **swaps, revoke_order()  without *order_nos PRODUCES errors** as
  _ File "E:\Pyth\lib\site-packages\alpha\platforms\huobi_swap_trade.py", line 398, in revoke_order
    success, error = await self._rest_api.revoke_order_all(self._symbol, '', self._contract_type)
TypeError: revoke_order_all() takes 2 positional arguments but 4 were given_

where _symbol is 'BTC-USD' and _contract_type is 'SWAP'.

**Is difference in using revoke_order() in swaps DIFFERENT FROM futures?**

Best regards,
Ingyu

**Comment by igkoh** [comment]
Explicit list of order numbers less or equal to 10 is properly cancelled in Swaps
           _order_nos=order_nos[:10]
            _, errors = await self.trader.revoke_order(*order_nos)_

**Comment by foonsun** [comment]
@igkoh I will check this issue.

**Comment by foonsun** [comment]
@igkoh The bug has been fixed.You can try it again.

**Comment by igkoh** [comment]
@foonsun , 
As you have instructed in alpha/platforms/huobi_swap_trade.py,
        _if len(order_nos) == 0:
            ##success, error = await self._rest_api.revoke_order_all(self._symbol, '', self._contract_type)
            success, error = await self._rest_api.revoke_order_all(self._symbol),_
I **confirmed successful cancellation of all open orders**

Thanks a lot.
Ingyu

**Comment by foonsun** [comment]
@igkoh thanks for your confirmation.
