### ISSUE TITLE
刚运行时，偶尔出现 trade 里 sub_callback，没反馈

### ISSUE THREAD

**Issue by qq71151461** [hbdmapi/hbdm_Python#24]
我这业务是当以下三个变量为True，才能正常交易
self._subscribe_order_ok = True
self._subscribe_position_ok = True
self._subscribe_asset_ok = True
软件刚运行时【多个账号多合约模式，即每个合约，会开启一个WS】，偶尔会出现某个账号的合约，以上三个变量没有全部为True。
暂无日志，因为不是频繁出现这种情况。

**Comment by foonsun** [comment]
已记录，将尝试复现此问题；

**Comment by foonsun** [comment]
目前仍无法复现；
