### ISSUE TITLE
rest_api 有没有办法获取账户相应合约的每日的收益盈亏情况[划转的不算]

### ISSUE THREAD

**Issue by qq71151461** [hbdmapi/hbdm_Python#27]
现在需要同步账户N天的财务记录，来计算；耗你们服务器资源，也耗我们服务器的资源。
另：
建议rest api 财务记录，委托历史记录等，增加以日期范围查询的功能，日期以年月日为单位

**Comment by foonsun** [comment]
@qq71151461 目前财务记录仍是原接口， rest api财务记录、委托历史记录，增加日期范围查询功能：这些接口目前已经在测试中，请留意上线公告；

**Comment by qq71151461** [comment]
嗯，可以的话，尽量再增加一个日收益盈亏报表
