### ISSUE TITLE
历史k线

### ISSUE THREAD

**Issue by Lxtluck** [hbdmapi/hbdm_Python#29]
async def on_ticker(self, *args, **kwargs):
        """ 定时执行任务
        """
        ts_diff = int(time.time()*1000) - self.last_orderbook_timestamp
        if ts_diff > self.orderbook_invalid_seconds * 1000:
            logger.warn("received orderbook timestamp exceed:", self.strategy, self.symbol, ts_diff, caller=self)
            return
        url = 'https://api.hbdm.com/market/history/kline'
        data = {"symbol":"eth_CQ","period":"30min","size":"20"}
        hkilne = requests.get(url,params=data)
        logger.info(hkilne)
        await self.cancel_orders()
        await self.place_orders()

这样写可以吗

**Comment by foonsun** [comment]
不要这样写，框架是异步库，可以直接使用rest接口去访问就可以，比如：

```python
         success, error = await self.trader.rest_api.get_klines("BTC", "1min",  1000)
         if error: 
            logger.error("Get swap market index faild:", error, caller=self)
        else:
           # Write your logic here
```
