### ISSUE TITLE
请问下在行情模块，不能自定义k线周期吗？

### ISSUE THREAD

**Issue by JamesChengHF** [hbdmapi/hbdm_Python#3]
默认只是1分钟的，没看到可以自定义设置

**Comment by JamesChengHF** [comment]
可以把配置周期的参数设置，从const文件配置到到config.json文件吗

**Comment by foonsun** [comment]
目前只支持1MIN K线，本系统主要是做高频量化用途，后续会考虑是否支持其他MIN K线。您也可以在这里自定义加入。https://github.com/hbdmapi/hbdm_Python/blob/master/alpha/platforms/huobi_swap_market.py#L90
