### ISSUE TITLE
Different Order book  behavior of swaps and futures 

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#34]
Theoretically **swaps of tick size 0.1 compared to futures 0.01, thus swaps of ask1 volume = sum of ask 1- 10 of futures.**
  
In reality, **swaps have much thicker ask1 and bid1 volume** compared against sum of ask1-10 and bid1-10 of futures.
**Why this fundamentally different behavior between swaps and futures**?

Best regards,
Ingyu

**Comment by igkoh** [comment]
This thickening of ask1 and bid1 in swaps compared to those of futures is also shared in Eth  Quarterly and Swap.

**Comment by igkoh** [comment]
Eth and BCH order books are more evenly spaced compared BTC's excessive concentrations on ask1 and bid1.   Order books of equity and S&P, Nasdaq and Dow Jones futures show evenly spaced ask and bid.  One way to understand this peculiarity of BTC is to accept and to profit from this concentrations on ask1 and bid1.  Still intuitive reasoning why focus on ask1 and bid1 in BTC can be extremely useful.

**Comment by foonsun** [comment]
Hi @igkoh The tick with 0.01 in swap compared to 0.001 in futures can provide better liquidity. The liquidity is better now.

**Comment by foonsun** [comment]
We will feedback this advice and discuss it later.
