### ISSUE TITLE
Usage of Log for diagnostics

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#35]
In continuous improvement of market making strategies, crucial tools are "LOG" in config.json.
It is hard to find
where the problem ( strange unpredictable occurs in execution of codes) lies.  As in my "strange" experience of double execution of place_orders
in large loop of trader.create_orders, **very detailed logs are TOOLS from where the 
diagnosis, hypothesis, and final resolution of problems.**
1. **For diagnosis, VERY DETAILED logs are required.**   
Does too detailed large volume of logs  impede low latency?   **I cannot find async/await in logger.py
     to minimize latency.  How low latency in logging is achieved in code?**  In my previous application, 
I used multi thread for logging to reduce latency.
2. 
        "console": false,   <-- write to file path/name, true: to the console  
        "level": "DEBUG",   <-- most detailed information for diagnosis
        "path": "/data/logs/servers/future_maker_strategy",
        "name": "future_maker_strategy.log",
        "clear": false,     <-- _??? do not clear, keep file permanently ???_
        "backup_count": 0   <-- _???save all log files permanently for later analysis???_
		
	File future_maker_strategy.log is confirmed at directory root/data/logs/servers/future_maker_strategy
In config.json, meaning of "**clear" : false**   _??? do not clear, keep file permanently ???_
                                                 **"backup_count": 0**   <-- _???save all log files permanently for later analysis???_

 Have I understood correctly?

3. **file and directory happen to disappear.**

Best regards,
Ingyu

**Comment by foonsun** [comment]
Hi, @igkoh We will try to add more logs when error happens.
```
"clear": false,     <-- _??? do not clear, keep file permanently ???_  It means flush the log or not.
 "backup_count": 0   <-- _???save all log files permanently for later analysis???_  It means the max backup count for logs.
```
file and directory happen to disappear.

--- You can set "clear": False, "backup_count": 30 to avoid the issues.

**Comment by igkoh** [comment]
@foonsun,
If clear is true, then shutil.rmtree(log_path) in initLogger of logger.py
removes  the log directory  at manage shell utility.

getFlesToDelete in Pyth/Lib/logging/handlers.py is removed by os.remove.
If getFlesToDelete is [] by if len(result)<30

I appreciate your deep knowledge of subject which clarifies very perplexing behavior of codes.
Thanks,
Ingyu

**Comment by foonsun** [comment]
Yes.It will removethe log directory if clear is true.
