### ISSUE TITLE
More frequent on_event_position_update, subsampling of on_event_trade_update and on_event_orderbook_update

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#36]
By analyzing the log information in swap,
updated frequencies of each method are:
_on_ticker     4442
cancel_orders   4442
place_orders    4442
position update  1292
asset update    1932
kline update     5616
orderbook       99472
trade update    52824_

Since async on_ticker calls
        await self.cancel_orders()
        await self.place_orders(),
the same number of on_ticker=cancel_orders=place_orders.

 **Since strategy depends on position for closing and entry price**,
can one control to have **more frequent update position**?
		
In extreme market condition, o**rderbook(20 times of on_ticker) and trade update(10 times of on_ticker) causes overloading of system,
can one subsample orderbook and trade like 1/5 in extreme market condition**?

Best regards,
Ingyu

**Comment by foonsun** [comment]
Hi, @igkoh 

Since strategy depends on position for closing and entry price,
can one control to have more frequent update position?

A: If you need to have more frequent update position,you can query the postion by the restful interface. 

In extreme market condition, orderbook(20 times of on_ticker) and trade update(10 times of on_ticker) causes overloading of system,
can one subsample orderbook and trade like 1/5 in extreme market condition?

A: The orderbook and trade are updated once there is orderbook or trade event.I still have no better way to handle it.

**Comment by igkoh** [comment]
@foonsun,
Following your comments, rest_api interface is queried as

_position, error =  await self.trader.rest_api.get_position(self.symbol)_
with the correct answer
        {'status': 'ok', 'data': [{'symbol': 'BTC', 'contract_code': 'BTC-USD', 'volume': 2.0, 'available': 0.0, 'frozen': 2.0, 'cost_open': 12247.048309592923, 'cost_hold': 12247.048309592923, 'profit_unreal': -1.40774572778e-05, 'profit_rate': -0.00862036496786141, 'lever_rate': 10, 'position_margin': 0.001634454296571732, 'direction': 'buy', 'profit': -1.40774572778e-05, 'last_price': 12236.5}], 'ts': 1597730421131}

question:  snce the return from query is synchronous return from rest_api, why I need await in front of trader.rest_api.get_position.
If the "await" is ommitted, error message 
builtins.TypeError: 'coroutine' object is not iterable.
Is await required only for the syntax rule?

**Comment by igkoh** [comment]
Why on_event_position_update and rest_api.get_position return DIFFERENT informations?  For example, in "on_event_position",
_'D [2020-08-18 00:00:00,861] [-] [MyStrategy] position update: [platform: huobi_swap, account: ingyukoh@gmail.com, strategy: my_test_strategy, symbol: BTC-USD/SWAP, short_quantity: 0, short_avg_price: 0, long_quantity: 0, long_avg_price: 0, liquid_price: None, utime: 1597676401229] '_
 "available" is not in return, while rest_api.get_position has "available" key-value.

**Comment by foonsun** [comment]
> @foonsun,
> Following your kind comments, rest_api interface is queried as
> 
> _position, error = await self.trader.rest_api.get_position(self.symbol)_
> with the correct answer
> _{'status': 'ok', 'data': [{'symbol': 'BTC', 'contract_code': 'BTC-USD', 'volume': 2.0, 'available': 0.0, 'frozen': 2.0, 'cost_open': 12247.048309592923, 'cost_hold': 12247.048309592923, 'profit_unreal': -1.40774572778e-05, 'profit_rate': -0.00862036496786141, 'lever_rate': 10, 'position_margin': 0.001634454296571732, 'direction': 'buy', 'profit': -1.40774572778e-05, 'last_price': 12236.5}], 'ts': 1597730421131}_
> 
> Question: since t**he return from query is synchronous return from rest_api**, **why I need "await" in front of trader.rest_api.get_position.**
> If the "await" is dropped, **error message builtins.TypeError: 'coroutine' object is not iterable.**
> Is await required only for the syntax rule?
> 
> Best regards,
> Ingyu

yes,await is required only for the syntax rule.

**Comment by igkoh** [comment]
@foonsun, await is pythonic discipline for syntax.   Thanks

**Comment by foonsun** [comment]
> available
