### ISSUE TITLE
HBDM Swap docs has stale field names and sample JSON from Futures docs

### ISSUE THREAD

**Issue by ebenali** [hbdmapi/hbdm_Python#37]
* https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#query-trigger-order-open-orders
 specifies `contract_type | string | true | Contract Type` but the example to the right has no such field.

* https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#place-trigger-order : same

* https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#subscribe-order-data-sub : the example to the right shows a snippet JSON with `contract_code` and `contract_type` set to `BTC200626` and `quarter`, respectively

This is a repost of the original issue in https://github.com/hbdmapi/huobi_swap_Cpp/issues/1#issue-693541867 for greater visibility

**Comment by foonsun** [comment]
@ebenali Hi,this json config of the example for the swap has been encapsulated.eg:https://github.com/hbdmapi/hbdm_Python/blob/master/examples/huobi_swap/strategy.py#L64

The example for swap:https://github.com/hbdmapi/hbdm_Python/tree/master/examples/huobi_swap

The config example for swap:https://github.com/hbdmapi/hbdm_Python/blob/master/examples/huobi_swap/config.json#L36

**Comment by ebenali** [comment]
> The `contract_type` field in the JSON config is to indicate the positions of the swap.It will not be passed as parameters when posting requests.

Thanks for the quick response. What of the `contract_code` field, it still shows [in the docs]
(https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#subscribe-order-data-sub):
```typescript
{
    "op": "notify",
    "topic": "orders.btc",
    "uid": "10086",
    "ts": 1590475967607,
    "symbol": "BTC",
    "contract_type": "quarter",
    "contract_code": "BTC200626",
    ...
}
```

**Comment by foonsun** [comment]
Hi @ebenali It will be fixed later.Thanks for your feedback.
