### ISSUE TITLE
delta hedge through Swap instead of Futures of same expiration date

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#39]
In huobi_option_mm, **delta_hedging create_orders through swap_trader for delta neutrality**.
For example, **call option exercise price 10500 at expiration date 0911 (BTC0911C10500-Weekly)** 
is  to **hedged through BTC0911 Weekly futures,** **instead of swap which is perpetual.**
Put-call (of same exercise price) parity equation also states c-p ~ F with the same expiration date for future approximately **replacing underlying assets by futures**.
**Why do you choose swap instead of futures of the same expiration date?**

Best regards,
Ingyu

**Comment by foonsun** [comment]
Hi @igkoh ,the delta of swap is approximate 1, however, the delta of future can change because of the basis. To hedge the delta more precisely, we choose the swap.

**Comment by igkoh** [comment]
For example, currently index price 10179, while future is 10184(basis 5 contango ) and swap 10172(-7 relative to index).
Swap is approximately of delta 1, not much affected by basis and controlled by funding rate.   Thus we neutralize
delta with swap. 

We **sell options with high implied volatility and large theta decay (weekly) near expiration** date.   If options are out-of-money(OTM) with low delta,
just take profit.  But market movement **makes options to in-the-money(ITM) with large delta(positive for call and negative for put),
take hedge position with swap in delta_hedging**.  Dynamical adjustment with combined option and swap MM are exciting fields
to be explored in Huobi.

Best regards,
Ingyu

**Comment by foonsun** [comment]
@igkoh Great! Thanks for your feedback.
