### ISSUE TITLE
HBDM Swap API doc: request to clarify/fix

### ISSUE THREAD

**Issue by ebenali** [hbdmapi/hbdm_Python#40]
In https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#get-information-of-an-order and throughout the rest of the document, the field 'liquidation_type' is described as being of type string but in this particular section, the two samples to the right show a numeric type.
```
  "liquidation_type": 1
```

**Comment by foonsun** [comment]
Hi, @ebenali thanks for your feedback. "liquidation_type" should be of type string. we have fixed it.thanks for your feedback again.
