### ISSUE TITLE
what is the problem?

### ISSUE THREAD

**Issue by IUYSY** [hbdmapi/hbdm_Python#5]
[HuobiSwapTrade] Websocket connection authorized failed: {'op': 'auth', 'type': 'api'
, 'ts': 1593934274973, 'err-code': 2003, 'err-msg': 'Verification failure [校验失败]'}

**Comment by foonsun** [comment]
> [HuobiSwapTrade] Websocket connection authorized failed: {'op': 'auth', 'type': 'api'
> , 'ts': 1593934274973, 'err-code': 2003, 'err-msg': 'Verification failure [校验失败]'}
You need to check whether your api key is correct.
