### ISSUE TITLE
logic of strategy  example

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#7]
In Trading System for MarketMakers, the strategy is in strategy.py as
    **if  volume is long,
	   sell at bid1 price with volume as free asset**

	   in examples/huobi_future/strategy.py lines:142-151 
	   
            _price = round(self.bid1_price + 0.1, 1)
            volume = float(self.trader.assets.assets.get(self.raw_symbol).get("free")) * price // 100 
            if volume >= 1:
                quantity = - volume #  空1张
                action = ORDER_ACTION_SELL
                new_price = str(price)  # 将价格转换为字符串，保持精度
                if quantity:
                    orders_data.append({"price": new_price, "quantity": quantity, "action": action, "order_type": ORDER_TYPE_LIMIT, "lever_rate": 1})
                    self.last_bid_price = self.bid1_price_
					
Is this line **just demonstration** or has implications **why this is profitable strategy?**

Best regards,
Ingyu

**Comment by foonsun** [comment]
@Ingyu This line is just demonstration.It may not be profitable strategy.
