### ISSUE TITLE
which trade.py  to use : either in Pyth/Lib/site-package/alpha/trade.py or hbdm_Python/alpha/trade.py

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#9]
In https://github.com/hbdmapi/hbdm_Python  ,
S**tepping  into Trade(line97) in strategy.py in goes into Pyth/Lib/site-package/alpha/trade.py instead of hbdm_Python/alpha/trade.py**.Relevant import in strategy.py(line 16) is:
_from alpha.trade import Trade_
**How can I change the import to use hbdm_Python/alpha/trade.py instead of Pyth/Lib/site-package/alpha/trade.py?**  Motivations are: use different trade.py implementation for different strategies.

Best regards,
Ingyu

**Comment by foonsun** [comment]
You can set PYTHONPATH to import the packages you need.
such as,
```
export PYTHONPATH=$PYTHONPATH:/home/workspace/hbdm_Python/
```

**Comment by igkoh** [comment]
Thanks for precise answer for using trade.py in hbdm_Python/alpha.

**Comment by foonsun** [comment]
@igkoh Np.
